# Generated by Django 2.2.1 on 2019-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('nome', models.CharField(max_length=75)),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('rua', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cep', models.IntegerField()),
            ],
        ),
    ]
