# Generated by Django 2.2.1 on 2019-06-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='funcionario.Funcionario')),
            ],
        ),
    ]
