# Generated by Django 2.2.1 on 2019-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='quantidade_vendas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
